server:
  port: 8009

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://${DB_HOST:47.92.67.120}:${DB_PORT:3306}/${DB_NAME:kafeim}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: ${DB_USER:kafeim}
    password: ${DB_PWD:dL7W2HBSGYcFjPNS}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
